### PR TITLE
Pv for phoebus vtype

### PR DESCRIPTION
**Pull request by kasemir**
For #68 :

Adjust build.xml to compile core-util and core-vtype.
(Note Eclipse project renamed from just 'util' to 'core-util').

Update core-pv to use it (instead of external diirt.vtype).

Add pva:// to core-pv.
pva is using the older pvAccessJava-4.0.3 currently found in dependencies.
To actually connect to more recent PVA servers, would need org.epics.pvAccessJava_4.1.3.jar or newer.

### CODE REVIEW

**Comment by kasemir** [comment]
Travis fails with
```
Downloading Oracle Java 9...
--2017-10-19 17:11:44--  http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz
..
HTTP request sent, awaiting response... 302 Moved Temporarily
..
HTTP request sent, awaiting response... 404 Not Found
```

**Comment by kasemir** [comment]
Includes the .classpath additions for Eclipse 4.7.1a, so now loads and runs right away.

Note: Commented the javax.annotation calls in EMail because of #52

**Comment by shroffk** [comment]
ok, with the updated travis file this PR should be ready to merge... @kasemir can you rebase this branch on master

**Comment by kasemir** [comment]
OK, had to fix a maven problem, now passes.

**Pull request merged**
