### PR TITLE
Build svg

### PR DESCRIPTION
**Pull request by kasemir**
#1023 and #1025 added SVG support, but didn't add the new test/resources folder to the .classpath, didn't list the new batik and XML libs in the dependencies .classpath, and set batik.version in both the parent pom and a lower pom.

### CODE REVIEW

**Comment by georgweiss** [comment]
Following the procedure in the README I am capable of building with both maven and ant without this commit. What am I missing? What do I need to do in order to detect build issues?

**Comment by kasemir** [comment]
What IDE are you using?

**Comment by georgweiss** [comment]
IntelliJ. And command line to test build, since that is what the CI is using.

**Comment by kasemir** [comment]
I think we all check building with maven.
Kunal then imports the maven projects into Eclipse, which doesn't always work perfectly.
You import them into IntelliJ, which seems to work perfectly.
I also build with ant, and I appreciate that you checked that.
In addition, I import into Eclipse via plain Eclipse projects (.project, .classpath).

==> I check maven, ant, eclipse.
You checked maven and ant.
Kunal checks maven.

**Comment by shroffk** [comment]
I have given up importing projects as maven in eclipse. With the presence of the classpath this always has problems with resolution etc.

I am sorry for my preference towards maven.
While I have ci tasks set up for maven which is why for open PR I usually only check maven I will start testing more religiously with ant too.
I really don't want to test with eclipse and the mangled .classpaths that I eventually land up with to just get things to work.

**Comment by georgweiss** [comment]
Well, IntelliJ is not perfect, but I rarely have issues. Plus if I fix the issues, they stay fixed.
Once you cover some mileage with IntelliJ you will realize it does a lot of small things much better than Eclipse. When summed up, that clearly compensates for the small amount of pain points.

**Comment by shroffk** [comment]
Ok I think I will start moving to intellij

I will continue to check the maven build and ant from command line.

**Comment by kasemir** [comment]
> I have given up importing projects as maven in eclipse. With the presence of the classpath ...

The .classpath files are for the plain Eclipse import.
When using the maven import, Eclipse updates them, and the result seems to help nobody.
Does the maven import work when you delete all .classpath files?

Then we could do this:
a) Use "Import existing Eclipse project" to use the .classpath as they are
b) Run some 'delete all .classpath' script, then import as maven project, where Eclipse now creates proper .classpath files from scratch.

**Comment by shroffk** [comment]
With other maven projects, when I import them as maven projects...eclipse generates the .classpath files and I don't touch them. This works.

> Then we could do this:
> a) Use "Import existing Eclipse project" to use the .classpath as they are
> b) Run some 'delete all .classpath' script, then import as maven project, where Eclipse now creates proper .classpath files from scratch.

Thanks, but I don't see the value in spending this effort. In eclipse we should advertise that we only support importing as eclipse projects. I have been doing the same and am fine with this.

I have run configurations defined for building using maven and ant which work very reliably...even when the workspace shows errors.

My bigger issue with eclipse is that even when importing **as eclipse projects** the workspace frequently goes into error states that make no sense.
See #1017, which disappear when you close or refresh or other random stuff...but I guess the answer to that lies in intellij

**Comment by kasemir** [comment]
> import them as maven projects...eclipse generates the .classpath .. works
> I don't see the value in spending this effort.

For Mac and Linux, it's trivial:
`find . -name .classpath -exec rm {} \;`

If you have a way to delete all .classpath files on Windows, then we can support both using the .classpath files or re-creating them from a maven import.

**Comment by kasemir** [comment]
based on https://superuser.com/questions/1142143/deleting-all-files-that-start-with-certain-pattern-windows-command-line, this might work for the Windows power shell:
```
$curDir = Split-Path -Parent $MyInvocation.MyCommand.Path
foreach ($file in Get-ChildItem -force $curDir -Recurse)
{
    if (($file.Extension -match '.classpath'))
    {
        Remove-Item $file.FullName -Force | Out-Null
    }
}
```

**Pull request merged**
