### PR TITLE
Code conventions

### PR DESCRIPTION
**Pull request by kasemir**
Initial writeup for #894, also mentioning file locations, naming of tests etc. which had been discussed in hangouts but should be documented with the code base.

### CODE REVIEW

**Comment by georgweiss** [comment]
Do not quite agree that we should label the following as discouraged:
`if(){
}
else{
}`

IDEs are capable of highlighting opening braces so finding them should not be a problem.

**Comment by kasemir** [comment]
I thought in #894 and hangouts we had already agreed on balanced braces.

**Comment by georgweiss** [comment]
Maybe, do not quite recall. But how are we to enforce it? Are we do change all source?

**Comment by kasemir** [comment]
We don't enforce it by blindly applying some source code formatter, that's kind of the point, because it would break all the manual formatting that people already put it.
These are suggestions for humans to follow as they add code or update some existing code.
Step one is to document it.
Step two might be enabling IDE support for removing trailing white space, or 4-spaces-instead-of-tabs. But no blind overall reformatting.

**Comment by georgweiss** [comment]
That's fine, but I still do not agree with the statement of discouraged use of braces.

**Comment by kasemir** [comment]
OK, then we scratch this.

**Pull request closed without merging**
