### PR TITLE
Formula PV

### PR DESCRIPTION
**Pull request by kasemir**
As discussed at developers meeting, a skeleton for formula PVs.

PVs now support "eq://expression" with shortcut "=expression".

Expression is numeric based on core-formula, with \`SomePV\` to include the value of PVs.

Example shows formula PV 
```
=`sim://sine` + `sim://ramp` + 15
```

plotted in comparison to its input PVs

eq

### CODE REVIEW

**Comment by pavel-ch** [comment]
The `phoebus/core/pv/src/main/resources/pv_formula_preferences.properties`  is referenced as `pv_eq_preferences.properties` from the code `class FormulaPVPreferences` -> Exception

**Comment by kasemir** [comment]
Good catch. Don't understand how I missed that.
#691

**Comment by pavel-ch** [comment]
Extremely useful feature.
Would it be possible to have a public access to formula PV's list of underlying PVs (or minimally PV names)? Example use case: custom Tooltip with some debug info etc.

**Comment by kasemir** [comment]
Well, you'd have to check `if (some_pv instanceof FormulaPV) ..`.
Are you then suggesting to add something like `String getExpression()` and `Collection<PV> getInputs()` to the `FormulaPV`?

**Comment by pavel-ch** [comment]
Yes exactly. The check `if (some_pv instanceof FormulaPV) ...` is legal because formula PVs are a) fixed part of Phoebus and b) something extraordinary having more PV inputs.
From my understanding, the `Collection<PV> getInputs()` on `FormulaPV` is enough. The expression string itself is clearly visible from the formula PV name.
I think this can be useful for formula debugging ui in any form. Some form of ui (tooltip?) can eliminate lots of user questions in the future.

**Comment by kasemir** [comment]
OK, added that.
But go slow, this formula implementation is a skeleton for what we've discussed at the recent developer's meeting. A big missing part is an SPI mechanism for adding functions, based on requirements for handling the existing formula use of BNL NSLS-II BOY displays.

**Comment by pavel-ch** [comment]
Thank you. And I understand, there is no hurry, this was for a long run. No direct activity atm.

**Pull request merged**
