### PR TITLE
Ant build file

### PR DESCRIPTION
**Pull request by kasemir**
This adds support for building phoebus with ant and a dependencies.zip.
Such a target platform would of course need to be provided on some file server.
For now I use this (download times vary, for me it's a few seconds total):
````
# Get the phoebus sources (for now from the 'ant' branch until this is merged)
git clone -b ant https://github.com/kasemir/phoebus.git

# Get the target platform, unpack parallel to phoebus sources
wget http://ics-web.sns.ornl.gov/kasemir/dependencies.zip
unzip dependencies.zip
````

Building with Maven
-------------------------

Full rebuild:
```
rm -rf ~/.m2
mvn clean install -f core/pom.xml
mvn clean install -f applications/probe/pom.xml
mvn clean install -f applications/logbook/pom.xml
mvn clean install -f applications/greetings/pom.xml
mvn clean install -f phoebus-product/pom.xml
```

Rebuild:
```
mvn install -f core/pom.xml
mvn install -f applications/probe/pom.xml
mvn install -f applications/logbook/pom.xml
mvn install -f applications/greetings/pom.xml
mvn install -f phoebus-product/pom.xml
```

Running:
```
java -jar phoebus-product/target/product-0.0.1-SNAPSHOT.jar 
```

Building with Ant
---------------------

Full rebuild:
```
ant clean product
```

Rebuild:
```
ant
```

Running:
```
# Either
java -jar phoebus-product/target/product-0.0.1.jar
# or just 
ant run
```

Comparison
----------------
 
Full Build, mvn:  1m20sec
Full Build, ant:     4sec

Run build again, no changes, mvn: 15 sec
Run build again, no changes, ant:  1 sec

Touch Probe.java, build again, mvn: 15 sec
Touch Probe.java, build again, ant:  2 sec

Lines of code in 9 pom.xml for mvn: 323
Lines of code in 1 build.xml for ant: 150

The ant build is not just faster.
Even more important, ant can build without network dependencies once the target ZIP and the sources have been obtained.
All builds are 100% reproducible because the target platform is just the ZIP file content.

### CODE REVIEW

**Comment by claudio-rosati** [comment]
I like Ant!!!

**Comment by shroffk** [comment]
Ok, as we agreed at the meeting those who prefer ant can use it while those who prefer maven can choose to use that.

With maven I like being able 
- define test dependencies, build profiles
- to only build modified modules (requiring full rebuilds points to problems with our project...and should not be the default process)
- not having manually go searching for dependencies or having to maintain binaries somewhere...we can still have the p2 repo tar hosted somewhere. 

Again, these are things that some of us prefer. There is no need to restrict the choice here, both can be supported.

**Comment by shroffk** [comment]
sorry, had to reopened to complete merge which seem to have not completed

**Comment by shroffk** [comment]
Maven offline build
```
mvn -o install

# core
[INFO] Reactor Summary:
[INFO] 
[INFO] core .............................................. SUCCESS [  0.223 s]
[INFO] framework ......................................... SUCCESS [  0.591 s]
[INFO] logging ........................................... SUCCESS [  0.037 s]
[INFO] types ............................................. SUCCESS [  0.035 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

# greetings
[INFO] Total time: 0.790 s

# logbook
[INFO] logbook ........................................... SUCCESS [  0.211 s]
[INFO] inmemory .......................................... SUCCESS [  0.564 s]

# Probe
[INFO] Total time: 0.811 s

# product
[INFO] Total time: 1.391 s

# Total time to build everything 3.863 s
```

Ant re-build 
```
init:
core-framework:
core-logging:
types:
applications-probe:
applications-greetings:
applications-logbook:
product:
BUILD SUCCESSFUL
Total time: 953 milliseconds
```

**Pull request closed without merging**
