### PR TITLE
Make SecondsParse independent of Locale

### PR DESCRIPTION
**Pull request by kasemir**
Fixes test failure in Europe,
#159

### CODE REVIEW

**Comment by claudio-rosati** [comment]
@kasemir 

That is not the only locale-related problem. Still not building:

```
Failures: 
  FormatOptionHandlerTest.testArray:263 
Expected: "[1.00, 2.00, 3.00, 4.00] V"
     but: was "[1,00, 2,00, 3,00, 4,00] V"
  FormatOptionHandlerTest.testCompact:240 
Expected: "65.43 V"
     but: was "65,43 V"
  FormatOptionHandlerTest.testDecimal:62 
Expected: "3.16"
     but: was "3,16"
  FormatOptionHandlerTest.testEngineering:125 
Expected: "31.6E-3 V"
     but: was "31,6E-3 V"
  FormatOptionHandlerTest.testExponential:106 
Expected: "3.160 V"
     but: was "3,160 V"

Tests run: 83, Failures: 5, Errors: 0, Skipped: 0

…
display ............................................ SUCCESS [  0.015 s]
display-model ...................................... FAILURE [ 34.960 s]
display-representation ............................. SKIPPED
…

```

**Comment by kasemir** [comment]
What do you get for `System.out.println(Locale.getDefault())` so I can reproduce this here?

**Comment by claudio-rosati** [comment]
en_SE

**Comment by kasemir** [comment]
OK, those tests now pass for me with both en_SE and en_US.
It's good that you run these tests in your locale. I'll continue here, so eventually we'll get all the differences.

**Comment by claudio-rosati** [comment]
Everything is fine now.
From a "locale" point of view this PR can be merged.

```
------------------------------------------------------------------------
Reactor Summary:

dependencies ....................................... SUCCESS [  8.027 s]
parent ............................................. SUCCESS [  0.016 s]
core ............................................... SUCCESS [  0.015 s]
framework .......................................... SUCCESS [  9.670 s]
util ............................................... SUCCESS [  3.571 s]
vtype .............................................. SUCCESS [  0.653 s]
pv ................................................. SUCCESS [  4.917 s]
ui ................................................. SUCCESS [  5.399 s]
logging ............................................ SUCCESS [  0.206 s]
types .............................................. SUCCESS [  0.122 s]
formula ............................................ SUCCESS [  1.113 s]
applications ....................................... SUCCESS [  0.008 s]
logbook ............................................ SUCCESS [  0.015 s]
inmemory ........................................... SUCCESS [  0.167 s]
olog ............................................... SUCCESS [  0.438 s]
logbook ui ......................................... SUCCESS [  0.142 s]
probe .............................................. SUCCESS [  0.168 s]
greeting-app ....................................... SUCCESS [  0.215 s]
pvtable ............................................ SUCCESS [  0.635 s]
pvtree ............................................. SUCCESS [  1.600 s]
logConfiguration ................................... SUCCESS [  0.213 s]
email .............................................. SUCCESS [  0.223 s]
rtplot ............................................. SUCCESS [  8.663 s]
databrowser ........................................ SUCCESS [ 12.932 s]
display ............................................ SUCCESS [  0.011 s]
display-model ...................................... SUCCESS [ 37.504 s]
display-representation ............................. SUCCESS [  4.447 s]
display-representation-javafx ...................... SUCCESS [  3.727 s]
display-runtime .................................... SUCCESS [ 26.416 s]
display-editor ..................................... SUCCESS [  2.417 s]
alarm .............................................. SUCCESS [  0.033 s]
alarm-model ........................................ SUCCESS [  1.355 s]
alarm-ui ........................................... SUCCESS [  0.609 s]
alarm-server ....................................... SUCCESS [ 41.810 s]
scan ............................................... SUCCESS [  0.013 s]
scan-model ......................................... SUCCESS [  0.514 s]
scan-client ........................................ SUCCESS [  0.198 s]
scan-ui ............................................ SUCCESS [  0.775 s]
scan-server ........................................ SUCCESS [  1.856 s]
file-browser ....................................... SUCCESS [  0.153 s]
Channel ............................................ SUCCESS [  0.014 s]
Channel Utility .................................... SUCCESS [  0.034 s]
channelfinder ...................................... SUCCESS [  0.354 s]
Channel Views ...................................... SUCCESS [  0.255 s]
product ............................................ SUCCESS [  0.818 s]
scan-server-product ................................ SUCCESS [  0.121 s]
alarm-server-product ............................... SUCCESS [  0.090 s]
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 03:03 min
Finished at: 2018-05-15T10:36:04+02:00
Final Memory: 41M/150M
------------------------------------------------------------------------
```

**Comment by kasemir** [comment]
Thanks for checking!

**Comment by claudio-rosati** [comment]
You're welcome.

**Pull request merged**
