### PR TITLE
Issue 218

### PR DESCRIPTION
**Pull request by shroffk**
should be merged with #268

### CODE REVIEW

**Comment by kasemir** [comment]
OK, looking at the dates, it seems you had started to fix some important broken things (bad pom, ignoring topic, no start script, no way to configure, ..) a week ago, but there was no pull request.
So I fixed the same things today, and added the build config.
==> We need to pull/merge more often to prevent duplicate work.

**Comment by kasemir** [comment]
I'll merge yours first, then fix the merge issues with my additions.

**Comment by shroffk** [comment]
logging.properties is good...we can surely have that.

the alarm_logging_properties allows the user to give a properties file instead on listing everything on the command line

`java -jar -properties /my/config/file.properties`

I have not been very regular sorry...

**Comment by shroffk** [comment]
@kasemir I do not have the shell commands which would be great to have too.

**Pull request merged**
