### PR TITLE
Issue 675

### PR DESCRIPTION
**Pull request by shroffk**
updating for the changes in alarm messages - combined state and config messages

### CODE REVIEW

**Comment by kasemir** [comment]
Maven runs into
```
[ERROR] Non-resolvable import POM: Failure to transfer org.springframework.boot:spring-boot-dependencies:pom:2.0.5.RELEASE from http://repo.maven.apache.org/maven2 ...
ReasonPhrase:Forbidden.
```

**Comment by shroffk** [comment]
I am fixing the builds...looks like travis is having some issues

**Comment by shroffk** [comment]
> Maven runs into
> 
> ```
> [ERROR] Non-resolvable import POM: Failure to transfer org.springframework.boot:spring-boot-dependencies:pom:2.0.5.RELEASE from http://repo.maven.apache.org/maven2 ...
> ReasonPhrase:Forbidden.
> ```

are you having this problem locally?

**Comment by kasemir** [comment]
No, travis has that problem.

**Comment by shroffk** [comment]
ok.. the builds are back up

**Pull request merged**
