### PR TITLE
Issue 136

### PR DESCRIPTION
**Pull request by shroffk**
Issue #136 and Issue #200

### CODE REVIEW

**Comment by shroffk** [comment]
@kasemir 
In the current channelfinder autocomplete, I directly query the service.
I tried to do this via an existing Job however the result of the query and the autocomplete table started getting out of order.

**Comment by kasemir** [comment]
That's OK. The completion implementation is already called on a background thread.
It should then do what it needs to do, and return the information when done.
See https://github.com/kasemir/phoebus-sns/blob/master/product-sns/src/main/java/org/phoebus/sns/completion/SNSPVProposals.java, it also connects to RDB etc.

**Comment by kasemir** [comment]
`channel/utility/.classpath` listed `src/test/resources`, which doesn't exist.
19c2c6120fba1d6467d446836cf179ef00e0c3a2 removed that in the ongoing alarm_actions branch.

The channel finder preference file, `channelfinder/src/main/resources/config/channelfinder.properties`, doesn't match the expected name for preference files (`*_preferences.properties`), so it's not included in the online help section that describes available settings (http://phoebus-doc.readthedocs.io/en/latest/preference_properties.html).
At this time, `core/mail` is a good example for handling preferences in the suggested way: Resource `*_preferences.properties` that's copied into the online help, with comment to indicate the package name,  and a `*Preferences` class that loads defaults via the `PreferencesReader`.

Since the `CFProposalProvider` is included in the default project, a default configuration for https://localhost:8181/ChannelFinder is fine, but would be good to have a way to disable it, instead of continuing to run into connection errors for a missing channel finder setup.
For example, setting `channelfinder.serviceURL` to nothing could be a way to disable channel finder lookups, but that results in NPE during application startup (which until 70c925c70c700ea4758d6e91cdafb703d1706a15 prevented phoebus from starting up at all).

**Comment by shroffk** [comment]
#200 has been updated

**Pull request merged**
