### PR TITLE
Issue 965

### PR DESCRIPTION
**Pull request by shroffk**
Moving the fxml into resources where it ideally belongs now that with the latest version of scene builder it no longer needs to be in the same src folder with the controller.

### CODE REVIEW

**Comment by shroffk** [comment]
@georgweiss I have updated the save and restore application also...please have a look to ensure I have not messed anything up

**Comment by georgweiss** [comment]
OK

**Comment by georgweiss** [comment]
There are a few changes needed for save-and-restore. Do you want me to push them to this branch?

**Comment by shroffk** [comment]
yes please

**Comment by shroffk** [comment]
Also, when trying to build the save restore applications (after importing into eclipse) I get the following error.
```
datamigration/git/GitMigrator.java: C:\git\phoebus\app\save-and-restore\ui\src\main\java\org\phoebus\applications\saveandrestore\datamigration\git\GitMigrator.java uses or overrides a deprecated API.
datamigration/git/GitMigrator.java: Recompile with -Xlint:deprecation for details.
ui/saveset/SaveSetController.java: Some input files use unchecked or unsafe operations.
ui/saveset/SaveSetController.java: Recompile with -Xlint:unchecked for details.
```

**Comment by georgweiss** [comment]
There are a number of other places where deprecated APIs are used. Suggest we create separate issues for all of them.
I merged with master, do you still want me to push?

**Pull request merged**
