### PR TITLE
Issue 218

### PR DESCRIPTION
**Pull request by shroffk**
- update the indices for state and command logging
- add remote git push support

### CODE REVIEW

**Comment by shroffk** [comment]
@tanviash some changes to the logger

**Comment by tanviash** [comment]
What does alarm commands mean?

**Comment by kasemir** [comment]
The XXXCommand topic, used by the client to send commands to the alarm server.
Commands are used to acknowledge or un-acknowledge alarms.

**Comment by shroffk** [comment]
So this will not record both the State and the Command messages...
https://github.com/shroffk/phoebus/tree/master/app/alarm

So we will have a record for both 
- when the user performs and action (acknowledges)
- when the alarm server sends out an associated state update (alarm state changes to Acknowledged)

**Comment by kasemir** [comment]
If all fails, read the documentation, https://github.com/shroffk/phoebus/blob/master/app/alarm/Readme.md, "Message Formats", "Command Topic"

**Comment by kasemir** [comment]
The messages are sent via the config, state and alarm topics because those 3 streams have different direction (who's sending?) and traffic volume. That might allow optimizing the Kafka config, like "Command" topic can simply delete old messages, while config and state can compact.

At the same time, the messages are such that you can tell from the content what type of message it is. In case a client simply reads from all topics, it doesn't have to check what topic delivered the message, the content tells all there is.

**Comment by tanviash** [comment]
Thank you Kunal & Kei.

**Comment by kasemir** [comment]
I'm OK with merging that.

**Pull request merged**
