### PR TITLE
Issue_32

### PR DESCRIPTION
**Pull request by shroffk**
Address issue #32 #15 #8

### CODE REVIEW

**Comment by kasemir** [comment]
@shroffk I'll turn the LoggingConfiguration into a singleton app similar to PV List: Will be saved/restored. Trying to open more than one will just show the existing one.

**Comment by kasemir** [comment]
@Kunal I'll remove the last 2 calls to the deprecated DockItem, the one without app descriptor: Greeting, Welcome.

**Comment by kasemir** [comment]
@shroffk The DockItem is now only available as `DockItem(AppInstance, content)`, so all tabs get saved & restored.

What'll be helpful now is a one-stop place to get all the applications, because we have several places where we iterate over all the `ServiceLoader.load(AppDescriptor.class)` and `ServiceLoader.load(AppResourceDescriptor.class)`:

 ```
ApplicationService:
    // Get app for the name
    // (May return AppDescriptor or AppResourceDescriptor)
    AppDescriptor getApp(String name);

   // Get apps for resource
   List<AppResourceDescriptor> getApplications(URL resource);
```

If  you want to keep the latter in `ResourceHandlerService`, or move that into a more generic `ApplicationService` doesn't make a difference to me.

**Comment by kasemir** [comment]
I think I found all places where we used to create another AppDescriptor instance.
Those now all get the one and only AppDescriptor for a name from the ApplicationService.
That's also used to start an app via "-app .." from the command line, but it's not yet passing any resources from the command line to that app.

Can do `-app pv_tree` but not `-app pv_tree?SomePVName`.

**Comment by kasemir** [comment]
Can do
```
-app pv_tree
-app probe
-app pc_table
```
=> AppDescriptor.create()

```
-resource /some/file.pvs
```
=> AppResourceDescriptor.create(that_resource)

TODO:
```
-app probe?pv=SomePVName
-app probe?file=SomePVName
-app pv_table?pv=a,pv=b
-app pv_table?file=/some/file.pvs
```
=> AppResourceDescriptor.create(that_resource)

**Comment by shroffk** [comment]
This might be becoming a bit too big
@kasemir should this be merged when the current build succeeds?

**Comment by shroffk** [comment]
@kasemir can we have a hangout?

**Pull request merged**
