### PR TITLE
Show placeholder for widgets with errors

### PR DESCRIPTION
**Pull request by krisztianloki**
This implements idea Nr. 2 of #968 .
Saving a display with unknown widgets should not be a problem; `PlaceholderWidget` retains the `Element` of the original widget and writes that one instead of itself.
There is one interesting thing; for some reason an exception is triggered when opening an incorrect display in edit mode:
```java
2019-12-05 14:09:22 WARNING [org.csstudio.display.builder.editor] Cannot obtain widget for display
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at org.csstudio.display.builder.model.WidgetFactory.getWidgetDescriptor(WidgetFactory.java:126)
	at org.csstudio.display.builder.editor.util.WidgetIcons.loadIcon(WidgetIcons.java:43)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.csstudio.display.builder.editor.util.WidgetIcons.getIcon(WidgetIcons.java:36)
	at org.csstudio.display.builder.editor.properties.PropertyPanelSection.bindSimplePropertyField(PropertyPanelSection.java:203)
	at org.csstudio.display.builder.editor.properties.PropertyPanelSection.createPropertyUI(PropertyPanelSection.java:504)
	at org.csstudio.display.builder.editor.properties.PropertyPanelSection.fill(PropertyPanelSection.java:166)
	at org.csstudio.display.builder.editor.properties.PropertyPanel.updatePropertiesView(PropertyPanel.java:141)
	at org.csstudio.display.builder.editor.properties.PropertyPanel.setSelectedWidgets(PropertyPanel.java:90)
	at org.csstudio.display.builder.editor.WidgetSelectionHandler.setSelection(WidgetSelectionHandler.java:67)
	at org.csstudio.display.builder.editor.WidgetSelectionHandler.clear(WidgetSelectionHandler.java:54)
	at org.csstudio.display.builder.editor.DisplayEditor.lambda$setModel$6(DisplayEditor.java:571)
	at org.csstudio.display.builder.representation.javafx.JFXRepresentation.execute(JFXRepresentation.java:669)
	at org.csstudio.display.builder.editor.DisplayEditor.setModel(DisplayEditor.java:571)
	at org.csstudio.display.builder.editor.EditorGUI.lambda$setModel$10(EditorGUI.java:525)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### CODE REVIEW

**Comment by kasemir** [comment]
>  for some reason an exception is triggered when opening an incorrect display in edit mode:
```
2019-12-05 14:09:22 WARNING [org.csstudio.display.builder.editor] Cannot obtain widget for display
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at org.csstudio.display.builder.model.WidgetFactory.getWidgetDescriptor(WidgetFactory.java:126)
```

WidgetFactory.java:126 fetches the widget by type name. Since the type name is not known, you get null.

This is happening in the editor when you select an unknown widget and the property panel thus tries to show the widget's icon, so it fetches the type info for the widget, which is unknown.

**Comment by krisztianloki** [comment]
Yes, but this exception is for the `display` itself. There is another one for the unknown placeholder widget that I did not pasted.

**Comment by kasemir** [comment]
> There is another one for the unknown placeholder widget that I did not pasted.

Are you done with this, ready to merge, or is there another exception that you need to fix?

**Comment by krisztianloki** [comment]
> > There is another one for the unknown placeholder widget that I did not pasted.
> 
> Are you done with this, ready to merge, or is there another exception that you need to fix?

I'm done with this, it is ready to be merged.
Sorry, my comment was a bit misleading; what I wanted to say is that the other exception is of the same type. So, there are two exceptions:
- an expected one because `UnknownWidget` has no descriptor (on purpose)
- an unexpected(?) one because `DisplayModel` has no descriptor. This was unexpected because I have never seen it so far...

**Pull request merged**
