### PR TITLE
kafka-config-path

### PR DESCRIPTION
**Pull request by shroffk**
it works with jdk 10 and 11

https://issues.apache.org/jira/browse/KAFKA-6855

### CODE REVIEW

**Comment by kasemir** [comment]
I'm just in the process up updating the Readme to kafka_2.11-2.0.0, the latest release, where this is no longer necessary. It works with Java 10.

**Comment by kasemir** [comment]
I'll merge, but the next update will remove that because no longer necessary

**Comment by shroffk** [comment]
Any plans on how/when we will upgrade? I am getting update fatigue :)

**Comment by kasemir** [comment]
For the USPAS training setup, I'm going through the notes and noticed that a new version is out, so I installed that and updated the Readme (kafka_update branch).
Works fine with out current client, which is using kafka-clients 1.1.0, but I'll look at updating to 2.0.0 tomorrow.

**Pull request merged**
