### PR TITLE
3d viewer

### PR DESCRIPTION
**Pull request by es-sns121**
Adding support for comments that can be added to shapes and then displayed as tooltips in the viewer.

 - [x] Unit tests for checkAndParseComment
 - [x] Unit tests for buildStructure
 - [x] Update pom.xml files for junit4 dependency.

### CODE REVIEW

**Comment by es-sns121** [comment]
Tests consistently fail due to TravisCI not being able to download Java 10.
Local tests on my machine with Java 10 produce no errors after compiling and testing with Maven.

**Comment by shroffk** [comment]
can you merge with the latest master...

**Comment by es-sns121** [comment]
There are no merge conflicts so sure. Are you asking me to or asking if I am able to?

**Comment by shroffk** [comment]
Sorry, I think I was not very clear.
I was asking you to merge master -> 3d_viewer
Once you do that, this PR should start building again.

**Comment by shroffk** [comment]
I think this merge should be fine...since you have tested it :)

**Comment by es-sns121** [comment]
Ok good. I was worried I had just messed up there.

________________________________

**Pull request merged**
