### PR TITLE
Databrowser raw warning

### PR DESCRIPTION
**Pull request by kasemir**
Import of https://github.com/ControlSystemStudio/cs-studio/issues/2524

### CODE REVIEW

**Comment by kasemir** [comment]
?? What change, what error?

**Comment by shroffk** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.2:compile (default-compile) on project core-ui: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/shroffk/phoebus/core/ui/src/main/java/org/phoebus/ui/dialog/AlertWithToggle.java:[15,28] package jfxtras.scene.layout does not exist
[ERROR] /home/travis/build/shroffk/phoebus/core/ui/src/main/java/org/phoebus/ui/dialog/AlertWithToggle.java:[66,19] cannot find symbol
[ERROR]   symbol:   class VBox
[ERROR]   location: class org.phoebus.ui.dialog.AlertWithToggle
[ERROR] /home/travis/build/shroffk/phoebus/core/ui/src/main/java/org/phoebus/ui/dialog/AlertWithToggle.java:[66,37] cannot find symbol
```

**Comment by kasemir** [comment]
Ah, yes. Something uses jfxtras, so auto-completion sometimes uses its classes instead of the normal JFX versions. I also sometimes get a List other than the plain Java List.

**Comment by shroffk** [comment]
I just see that my comment was not associated with the commit I wanted to comment on. sorry for the confusion.

**Comment by shroffk** [comment]
I merged this to get the master CI to pass again

**Comment by kasemir** [comment]
What's the problem with master CI?

**Pull request merged**
