### PR TITLE
Save-and-restore to Phoebus

### PR DESCRIPTION
**Pull request by georgweiss**
Originally developed on an branch "CSSTUDIO-909" on the ESS fork, I have kept the branch name.

Code additions are both save-and-restore service (aka JMasar) and application, invoked from the Utilities menu.

### CODE REVIEW

**Comment by kasemir** [comment]
Somewhat unclear why it's asking the top-level .gitignore to ignore .classpath and .project files, then changes those files in otherwise unrelated apps like 3dViewer, PVTree, ...

**Comment by georgweiss** [comment]
Will revert .gitignore. Also need to update some dependency versions as Travis is unable to build. How do I do this, close this PR and make a new one once I have pushed fixes?

**Comment by kasemir** [comment]
> How ..

Do whatever's easiest for you. Continue to update this branch, or use a new one.

**Comment by georgweiss** [comment]
Fixed some issues, please review.

**Comment by kasemir** [comment]
Build fails because it's looking for 0.0.1 versions, but based on your suggestion we updated to 4.6.0.
Merge also changes some .classpath and .project files in unrelated apps. Not sure if that's necessary, but we can fix that later in case it causes problems.

**Comment by georgweiss** [comment]
I'm working on this, no worries.

**Comment by kasemir** [comment]
You fixed the build!
I'm not in a good position to test this, but I suggest to merge so others can try it out.

**Comment by georgweiss** [comment]
Any objections to merge?

**Comment by kasemir** [comment]
Not from my side

**Pull request merged**
