### PR TITLE
Frib/springboot

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by kasemir** [comment]
Thanks, that helps build it.

This is missing for 'ant dist':
```
diff --git a/services/alarm-logger/build.xml b/services/alarm-logger/build.xml
index d9365bc..7d7f25b 100644
--- a/services/alarm-logger/build.xml
+++ b/services/alarm-logger/build.xml
@@ -42,6 +42,7 @@
         <include name="dependencies/**/snakeyaml-*.jar"/>
        <include name="dependencies/**/snappy-java-*.jar"/>
         <include name="dependencies/**/t-digest-*.jar"/>
+        <include name="dependencies/**/spring-*.jar"/>
                
        <include name="core/**/core-framework-*.jar"/>
        <include name="core/**/core-util-*.jar"/>
```


Two problems:

1) Minor: Even running it with '-help' starts spring and prints a lot of stuff.
Maybe it can first check arguments and then start spring as necessary?

```
alarm-logger]$ ./alarm-logger.sh -help

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.4.RELEASE)

[2018-10-25 13:32:00.030] - 6633 INFO [main] --- org.phoebus.alarm.logging.AlarmLoggingService: Starting AlarmLoggingService on diane.ornl.gov with PID 6633 (/home/ky9/git/phoebus/services/alarm-logger/target/service-alarm-logger-0.0.1.jar started by ky9 in /home/ky9/git/phoebus/services/alarm-logger)
[2018-10-25 13:32:00.059] - 6633 INFO [main] --- org.phoebus.alarm.logging.AlarmLoggingService: No active profile set, falling back to default profiles: default
[2018-10-25 13:32:00.105] - 6633 INFO [main] --- org.springframework.context.annotation.AnnotationConfigApplicationContext: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6a2b953e: startup date [Thu Oct 25 13:32:00 EDT 2018]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/ky9/git/phoebus/services/alarm-logger/target/lib/spring-core-5.0.8.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2018-10-25 13:32:00.659] - 6633 INFO [main] --- org.springframework.jmx.export.annotation.AnnotationMBeanExporter: Registering beans for JMX exposure on startup
[2018-10-25 13:32:00.675] - 6633 INFO [main] --- org.phoebus.alarm.logging.AlarmLoggingService: Started AlarmLoggingService in 0.854 seconds (JVM running for 1.097)
...
```

2) Major: Can no longer shut down. Entering the 'shutdown' command reaches the "Done." printout, but the process still lingers around. So I can no longer run it within procServ, which is what we use for all IOCs, scan server, archive engine, alarm server, ...:

```
alarm-logger]$ ./alarm-logger.sh 
...
 > help
Commands:
	help             - Show help.
	shutdown         - Shut alarm logger down and exit.

 > shutdown
 > 
Done.
2018-10-25 13:33:47 INFO [org.phoebus.alarm.logging] Shutting down the ElasticClientHelper.
2018-10-25 13:33:47 INFO [org.springframework.context.annotation.AnnotationConfigApplicationContext] Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@1f59a598: startup date [Thu Oct 25 13:33:40 EDT 2018]; root of context hierarchy

... and now just hangs there without exiting.
```

Maybe `SpringApplication.run()` needs to be optional, based on a command line option?

**Comment by shroffk** [comment]
I had tested the help and and it worked for me...I had not tried it with startup but post startup.

I am currently looking into the shutdown issue.

**Comment by kasemir** [comment]
The help works, but there's more printout from spring than actual help  ;-)  

The shutdown is clearly more important.

**Comment by shroffk** [comment]
I think the found a few fixes for the shutdown...can you double test if they work?

**Comment by kasemir** [comment]
Can't build with ant. Still need the `<include name="dependencies/**/spring-*.jar"/>`
already mentioned plus now the additional dependency on `spring-boot-starter-web`.

When I build with maven, `alarm-logger.sh` fails because it's looking for the previously created `service-alarm-logger-0.0.1-SNAPSHOT-jar-with-dependencies.jar`.

When I update that to use `service-alarm-logger-0.0.1-SNAPSHOT.jar`, invoking `-help` prints a lot of additional stuff and then hangs until I press Ctrl-C:

```
$ java -jar target/service-alarm-logger-0.0.1-SNAPSHOT.jar -help
2018-10-26 08:19:05.566  INFO 7428 --- [           main] o.p.alarm.logging.AlarmLoggingService    : Starting AlarmLoggingService on diane.ornl.gov with PID 7428 (/home/ky9/git/phoebus/services/alarm-logger/target/service-alarm-logger-0.0.1-SNAPSHOT.jar started by ky9 in /home/ky9/git/phoebus/services/alarm-logger)
2018-10-26 08:19:05.570  INFO 7428 --- [           main] o.p.alarm.logging.AlarmLoggingService    : No active profile set, falling back to default profiles: default
2018-10-26 08:19:05.621  INFO 7428 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@72967906: startup date [Fri Oct 26 08:19:05 EDT 2018]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/home/ky9/git/phoebus/services/alarm-logger/target/service-alarm-logger-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-core-5.0.8.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-10-26 08:19:06.719  INFO 7428 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9000 (http)
2018-10-26 08:19:06.764  INFO 7428 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-10-26 08:19:06.764  INFO 7428 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.32
2018-10-26 08:19:06.774  INFO 7428 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
2018-10-26 08:19:06.836  INFO 7428 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-10-26 08:19:06.836  INFO 7428 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1221 ms
2018-10-26 08:19:06.900  INFO 7428 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2018-10-26 08:19:06.904  INFO 7428 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-10-26 08:19:06.904  INFO 7428 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-10-26 08:19:06.904  INFO 7428 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-10-26 08:19:06.904  INFO 7428 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-10-26 08:19:07.002  INFO 7428 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-10-26 08:19:07.180  INFO 7428 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@72967906: startup date [Fri Oct 26 08:19:05 EDT 2018]; root of context hierarchy
2018-10-26 08:19:07.255  INFO 7428 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/alarm-history/search/{pv}],methods=[GET]}" onto public java.util.List<org.phoebus.applications.alarm.messages.AlarmStateMessage> org.phoebus.alarm.logging.rest.SearchController.searchPv(java.lang.String)
2018-10-26 08:19:07.256  INFO 7428 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/alarm-history/search],methods=[GET]}" onto public java.util.List<org.phoebus.applications.alarm.messages.AlarmStateMessage> org.phoebus.alarm.logging.rest.SearchController.search()
2018-10-26 08:19:07.260  INFO 7428 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2018-10-26 08:19:07.260  INFO 7428 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2018-10-26 08:19:07.294  INFO 7428 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-10-26 08:19:07.295  INFO 7428 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-10-26 08:19:07.428  INFO 7428 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-10-26 08:19:07.465  INFO 7428 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9000 (http) with context path ''
2018-10-26 08:19:07.470  INFO 7428 --- [           main] o.p.alarm.logging.AlarmLoggingService    : Started AlarmLoggingService in 2.3 seconds (JVM running for 2.801)
 _______  _        _______  _______  _______    _        _______  _______  _______  _______  _______ 
(  ___  )( \      (  ___  )(  ____ )(       )  ( \      (  ___  )(  ____ \(  ____ \(  ____ \(  ____ )
| (   ) || (      | (   ) || (    )|| () () |  | (      | (   ) || (    \/| (    \/| (    \/| (    )|
| (___) || |      | (___) || (____)|| || || |  | |      | |   | || |      | |      | (__    | (____)|
|  ___  || |      |  ___  ||     __)| |(_)| |  | |      | |   | || | ____ | | ____ |  __)   |     __)
| (   ) || |      | (   ) || (\ (   | |   | |  | |      | |   | || | \_  )| | \_  )| (      | (\ (   
| )   ( || (____/\| )   ( || ) \ \__| )   ( |  | (____/\| (___) || (___) || (___) || (____/\| ) \ \__
|/     \|(_______/|/     \||/   \__/|/     \|  (_______/(_______)(_______)(_______)(_______/|/   \__/

Command-line arguments:

-help                                    - This text
-topics   Accelerator                    - Alarm topics to be logged, they can be defined as a comma separated list
-es_host  localhost                      - elastic server host
-es_port  9200                           - elastic server port
-bootstrap.servers localhost:9092        - Kafka server address
-properties /opt/alarm_logger.propertier - Properties file to be used (instead of command line arguments)
-date_span_units M                       - Date units for the time based index to span.
-date_span_value 1                       - Date value for the time based index to span.
-logging logging.properties              - Load log settings

^C
2018-10-26 08:19:09.145  INFO 7428 --- [       Thread-2] ConfigServletWebServerApplicationContext : Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@72967906: startup date [Fri Oct 26 08:19:05 EDT 2018]; root of context hierarchy
2018-10-26 08:19:09.147  INFO 7428 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```


I understand that you really want to use SpringBoot, and I'm fine with that, but please understand that it worked very well without SpringBoot, and I'd like to keep using it that way for our setups.
After all, one lesson learned from CSS/Eclipse for me is that depending on other frameworks can be troublesome for control system software that needs to be maintained for decades.

So instead of `AlarmLoggingService.main()` always calling
```
       SpringApplication.run(..);
```
and then trying to clean that up, why not have two entry points:
1) The original `AlarmLoggingService`, maybe renamed to `AlarmLoggingServiceStandalone`
2) A new `AlarmLoggingServiceSpring` with a main like this:
```
public static void main(final String[] original_args) throws Exception
{
        context = SpringApplication.run(AlarmLoggingService.class, original_args);
        AlarmLoggingService.main();
}
```

Seems to me that would be best for both use cases. I can keep the standalone operation, while you can add whatever is needed for SpringBoot integration.

**Comment by willrogers** [comment]
I think Kay's right. If you can keep your application code free of external dependencies you are much freer to drop or swap them later. If you don't maintain that interface cleanly then there tends towards a creep where 5 years later it's too big a job to extricate them.

**Comment by shroffk** [comment]
> Can't build with ant. Still need the <include name="dependencies/**/spring-*.jar"/>

I have still not fixed this, I had focused on the shutdown and the banner.

> When I build with maven, alarm-logger.sh fails because it's looking for the previously created service-alarm-logger-0.0.1-SNAPSHOT-jar-with-dependencies.jar

This is a minor fix, actually now the *.sh file becomes even simpler since there is a single *.jar

**Comment by kasemir** [comment]
I agree that the fixed script would be simpler. Just reporting what I see, where `-help` went from being OK to having extra Spring messages to now having extra Spring messages plus requiring Ctrl-C.

**Comment by kasemir** [comment]
Sounds fine.
Implementation still seems easier if there are two 'main' classes, one for standalone and one for Spring.
I'm OK with the spring-main being the one mentioned in the jar manifest, and then I'll call
`java -jar that.jar path.to.AlarmLoggingServiceStandalone` to get what I've been using so far.
But always starting spring and then trying to undo that, even for a simple `-help`, seems to go the wrong way.

**Pull request merged**
