### PR TITLE
ES sniff feature for logging-ui

### PR DESCRIPTION
**Pull request by tanviash**
The change is similar to the one I made on alarm logger side. This is to enable ES sniff feature for logging-ui client so it can retrieve data from other cluster ES nodes in case of failover.

### CODE REVIEW

**Comment by tanviash** [comment]
@shroffk @kasemir Please review this code change.

**Comment by kasemir** [comment]
Sorry, I don't see anything new.
It needs a basic
```
  if (sniffer != null)
    sniffer.close();
```

Also, instead of `prefs.get("es_sniff").equals("true")` you can use `prefs.getBoolean("es_sniff")`

**Comment by kasemir** [comment]
Ah, I didn't know how to handle the 'review' feature. Had entered something, but failed to press some 'commit' button so I guess you never saw my original comment.

**Comment by kasemir** [comment]
Check the PreferencesReader. Instead of `Integer.valueOf(prefs.get("es_port")))))` you could use `prefs.getInt("es_port")`, and for `prefs.get("es_sniff").equals("true")` there's `getBoolean("es_sniff")`.
I can't test the cluster failover, so no idea if the change does anything to support it, but otherwise it looks OK to me.

**Pull request merged**
