### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by kasemir**
Import of Data Browser rule fix.

Preserve last "To:" value for email dialog.

Fix layout reload

### CODE REVIEW

**Comment by shroffk** [comment]
@kasemir in preparation for the appliance archiver plugin I did a little bit of code restructuring for the databrowser.
I am still working on it so it is not ready for PR but I thought I would let you know.

**Comment by kasemir** [comment]
OK, so let's merge this now to avoid too many open branches that might diverge.

**Comment by kasemir** [comment]
I'm unclear about Claudio's pull requests since one mentions "Don't merge yet" but then refers waiting for 307, which is itselve...

**Comment by kasemir** [comment]
Otherwise we should merge those as well.

**Pull request merged**
