### PR TITLE
Olog

### PR DESCRIPTION
**Pull request by shroffk**
Updated client for the new olog-es service.
WIP: do not merge since some core interfaces have minor updates.

### CODE REVIEW

**Comment by shroffk** [comment]
@kasemir 
I have made one change the core logbook api.
The client now asks the service for a list of supported levels. This is to allow different sites to allow different levels.

As with the in memory logbook, you can populate this list from a properties file packaged with your site specific client.

I hope this works with SNS client easily

**Comment by shroffk** [comment]
Additionally, where user defined times are uses I am reverting to using MILLI_FORMAT

**Comment by kasemir** [comment]
I saw the 'level'. We do have those, so I can implement it for our logbook. I didn't look into the olog detail, that's all yours.

**Comment by shroffk** [comment]
ya... the olog stuff is about the olog specific client.
Only the level, the associated create logentry dialog, and the query which uses MILLI_FORMAT should affect you.

**Comment by kasemir** [comment]
OK to use MILLI_FORMAT.

**Comment by kasemir** [comment]
If there were a logbook implementation that doesn't support levels, then you could consider supporting a UI that detects when the list of options is empty and thus removes that UI element.
But we can leave that for a time when it's necessary, since for now all supported logbooks have a 'level' (or 'priority' or something like that).

**Pull request merged**
