### PR TITLE
removing jdk10 from CI

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by shroffk** [comment]
I think we need to prepare to move to 11.
I propose removing jdk10 from the travis CI for the time being

**Comment by shroffk** [comment]
@kasemir @claudio-rosati 
I see that openjdk11 listed in the avaiable jdks...

**Comment by kasemir** [comment]
It builds with openjdk11 for me locally, so maybe we should enable that.
Only issue is running pvAccess, but that'll be fixed as we update the pvAccess lib, and doesn't affect the build.

**Comment by shroffk** [comment]
Ok... I will set this up for us to try

**Pull request merged**
