### PR TITLE
Patches

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by kasemir** [comment]
How do I best disable the channel finder to avoid these error messages:
```
2019-08-12 12:38:21 INFO [org.phoebus.channelfinder.autocomplete.CFProposalProvider] 
Failed to create Channel Finder PVProposalProvider
...
Connection refused
```

**Comment by shroffk** [comment]
Well, we could not include it in the product

**Comment by shroffk** [comment]
excluding the app-channel-utility jar should get rid of the error...

**Comment by kasemir** [comment]
I'm OK with including it.
Also OK to have localhost as default URL.
But have a way to disable, for example by setting the URL to empty.

**Pull request merged**
