### PR TITLE
Csstudio 1135

### PR DESCRIPTION
**Pull request by georgweiss**
Added tool to migrate save-and-restore data from git to service.

### CODE REVIEW

**Comment by kasemir** [comment]
`Node.NODE_DATE_FORMAT` could use the common  `org.phoebus.util.time.TimestampFormats.MILLI_FORMAT`

**Comment by georgweiss** [comment]
I'll change on next push.

**Comment by kasemir** [comment]
`app/save-and-restore/ui/pom.xml` adds `jgit` dependency.
Consider adding that to target platform, see https://github.com/shroffk/phoebus/blob/master/dependencies/README.md

**Comment by georgweiss** [comment]
Sure, haven't got used to use target platform (reminds me of Eclipse...)

**Comment by georgweiss** [comment]
Actually, the jgit dependency is already there in `dependencies/phoebus-target/pom.xml`.

**Comment by kasemir** [comment]
Good, thanks!

**Pull request merged**
