### PR TITLE
Issue 305

### PR DESCRIPTION
**Pull request by shroffk**
Needs reviews and input 

TODO:
system dependencies can be removed

### CODE REVIEW

**Comment by kasemir** [comment]
Let's merge this so I can fix the ant files and my beamline build & distribution setup.

**Comment by shroffk** [comment]
I tested the ant build also...added changes to the ant_settings

**Comment by kasemir** [comment]
Good, thanks.
I guess the basic build instructions remain:
Can either use `mvn -DskipTests clean install` from the top, or do that only for dependencies and then proceed with the `dependencies/phoebus-target/target/lib/`. Only difference is the added `phoebus-target` directory level.

**Comment by shroffk** [comment]
> I guess the basic build instructions remain

yes...I created the new modules to make sure that old build instructions work

> Only difference is the added phoebus-target directory level.

yes, we can put the output of phoebus-target into /dependencies...if we really want this...

**Comment by kasemir** [comment]
Some ant files still needed the `phoebus-target` added, now OK.

**Comment by kasemir** [comment]
Removed all systemPath entries from the pom.xml, only remaining one is for the Oracle JDBC jar.
Will move the profile that's enabled when `env.ORACLE_JDBC_JAR` is defined to install-jars, so oracle JDBC jar is installed in similar way, but instead of including a copy in git as with pbraw (which we cannot do for legal reasons) you must already have it & and point an environment var to it.

**Pull request merged**
