### PR TITLE
#4 test version of a file based multi system preferen…

### PR DESCRIPTION
**Pull request by shroffk**
…ces implementation""

WIP:
TODO persistence

### CODE REVIEW

**Comment by kasemir** [comment]
After I pull this, then try to start the LogManager, it ends with
```
Exception in thread "main" java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:364)
	at java.logging/java.util.logging.LogManager.readConfiguration(LogManager.java:1556)
```

**Comment by kasemir** [comment]
Sorry, ignore, I had deleted the phoebus-product/src/main/resources/logging.properties. All fine.

**Comment by kasemir** [comment]
My Eclipse IDE reported "Updates availalble" for the Java 9 support. I installed those, and ever since I keep getting strange errors.

**Comment by kasemir** [comment]
Compared to the Linux FileSystemPreferences, this one always creates a new, random-number based user root, so I cannot actually read the settings that were previously saved.
Can you remove the `createUniqueInstanceRoot()`?

**Comment by kasemir** [comment]
Regarding the IDE, the update to "Eclipse JDT (Java Development Tools) Patch with Java 9 support (BETA) for Oxygen development stream", 1.1.1.v20170826-0521_BETA_JAVA9, was a bad idea.

After I installed that, I suddenly got errors like "Can only iterate over an array or an instance of java.lang.Iterable error " for this type of code:
```
List<String> list = ...;
for (String item : list)
```

A Project/clean didn't help. Just typing that same code again would fix it, until the error suddenly reoccurred. Reverting back to the Java 9 support 1.1.1.v20170627, which was thankfully easy via Help/ About, Installation Details, .., Revert, the problems disappeared.

**Comment by shroffk** [comment]
> Can you remove the createUniqueInstanceRoot()?
Yes, this is a todo. I wanted to also figure out how the preferences should be persisted.

If you restart phoebus which preferences are remembered? especially when you have multiple instances how do you (if at all) do you pick and choose the preferences to be remembered between restarts.

**Pull request merged**
